### ISSUE TITLE
This library supports not only Russian IMO

### ISSUE THREAD

**Issue by fakeheal** [alexeymezenin/laravel-russian-slugs#1]
This library supports not only Russian. It can be used by any language with cyrillic characters. Correct me if I'm wrong.

**Comment by alexeymezenin** [comment]
@FakeHeal, well, I suppose it will work with any cyrillic language. Please look at [`toTranslit()`](https://github.com/alexeymezenin/laravel-russian-slugs/blob/master/src/Slugs.php#L110) which conatins the list of all cyrillic characters which will be converted.

**Comment by fakeheal** [comment]
@alexeymezenin I have used the same function for transliteration and there's an issue with it, that has been alway annoying me =D

If you have the following:

> Юлия Петровна

It will be transliterated to:

> Yuliya Petrovna

Which is cool, however if you have anything uppercased:

> ЮЛИЯ ПЕТРОВНА

It wil be transliterated to:

> YuLIYa Petrovna

_Notice the lowercase letters in it._

Is there any way cases like this to be avoided?

**Comment by alexeymezenin** [comment]
@FakeHeal, I never met anything like this. )

Actually, you can test it before use with simple closure like:

```
Route::get('test', function() {
    config(['seoslug.urlType' => 2]); // Just for testing stuff.
    echo Slug::build('ЮЛИЯ ПЕТРОВНА');
});
```

Which returns `yuliya-petrovna`.

**Comment by fakeheal** [comment]
So, actually it's always lowercase?

**Comment by alexeymezenin** [comment]
@FakeHeal, nope. You can set `'keepCapitals' => true,` in `config/seoslug.php`. Or `config(['seoslug.keepCapitals' => true]);` while you're testing with closure. This will keep capitals in URL.
